#include "ImageTexture.h"

// Register the derived class in the boost serialization framework.
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_Spectrum_f_Spectrum_f);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_Spectrum_f_Spectrum_d);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_Spectrum_d_Spectrum_d);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_SpectrumCoef_f_SpectrumCoef_f);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_SpectrumCoef_f_SpectrumCoef_d);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_SpectrumCoef_d_SpectrumCoef_d);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_float_float);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_double_double);
BOOST_CLASS_EXPORT_IMPLEMENT(ImageTexture_float_double);