; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	d:\Development\Source\Raytracer\TestTrace\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0P@GHFPNOJB@bad?5allocation?$AA@		; `string'
PUBLIC	___@@_PchSym_@00@UwvevolknvmgUhlfixvUizbgizxviUgvhggizxvUivovzhvUhgwzucOlyq@
___@@_PchSym_@00@UwvevolknvmgUhlfixvUizbgizxviUgvhggizxvUivovzhvUhgwzucOlyq@ DD 01H DUP (?)
__bad_alloc_Message DD FLAT:??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
;	COMDAT ??_C@_0P@GHFPNOJB@bad?5allocation?$AA@
CONST	SEGMENT
??_C@_0P@GHFPNOJB@bad?5allocation?$AA@ DB 'bad allocation', 00H ; `string'
END
